name: paretoboost
channels:
  - conda-forge
dependencies:
  - python>=3.6
  - xarray
  - netcdf4
  - dask
  - xesmf
  - numba
  - fire
  - numpy
  - matplotlib
  - cartopy
  - configargparse
  - tensorflow>=2.0   
  - ipykernel
  - scikit-learn
  - jupyterlab
  - pip
  - pip:
      - cdsapi

# for GPU support, make sure cudatoolkit and cudnn are installed 
# verify: python3 -c "import tensorflow as tf; print(tf.config.list_physical_devices('GPU'))"

# Here are the exact versions I used
#dependencies:
#  - python=3.10.4
#  - xarray=2022.3.0
#  - cartopy=0.20.2 
#  - tensorflow=2.8.1
#  - pip:
#      - cdsapi=0.5.1
